Valtech_Task3(Ankh-Morpork MVC)/Controllers/PlayerController.cs
using System.Threading.Tasks;
using System.Web;
using System.Web.Mvc;
using Microsoft.AspNet.Identity;
using Microsoft.AspNet.Identity.Owin;
using Valtech_Task3_Ankh_Morpork_MVC_.DataManager.Resources;
using Valtech_Task3_Ankh_Morpork_MVC_.Services;
using Valtech_Task3_Ankh_Morpork_MVC_.ViewModels.Player;

namespace Valtech_Task3_Ankh_Morpork_MVC_.Controllers
{
    [Authorize]
    public class PlayerController : Controller
    {
        private AccountPlayerManager PlayerManager => HttpContext.GetOwinContext().GetUserManager<AccountPlayerManager>();
        // GET: Player
        public ActionResult Index()
        {
            return View(PlayerManager.FindById(User.Identity.GetUserId()));
        }
        [HttpGet]
        public async Task<ActionResult> Edit(string id)
        {
            var player = await PlayerManager.FindByIdAsync(id);

            if (player == null)
            {
                return Content("Not found");
            }

            var model = new EditPlayerViewModel { Id = player.Id, Name = player.UserName };

            return View(model);
        }
        [HttpPost]
        public async Task<ActionResult> Edit(EditPlayerViewModel model)
        {
            var gameEngine = new GameEngine(User.Identity.GetUserId());

            if (!ModelState.IsValid) return View(model);

            var player = await PlayerManager.FindByIdAsync(model.Id);

            //var p = await CurrentPlayerProcessor.PlayerManager.FindByIdAsync(model.Id);

            if (player == null) return View(model);

            player.UserName = model.Name;

            //p.UserName = model.Name;

            var result = await PlayerManager.UpdateAsync(player);
            if (result.Succeeded)
            {
                //await CurrentPlayerProcessor.PlayerManager.UpdateAsync(p);
                return RedirectToAction("Index");
            }
            else
            {
                foreach (var error in result.Errors)
                {
                    ModelState.AddModelError(string.Empty, error);
                }
            }
            return View(model);
        }

        public ActionResult OutOfMoney()
        {
            return RedirectToAction("GameOver", "GamePlay");
        }
    }
}

Valtech_Task3(Ankh-Morpork MVC)/Controllers/TheMendedDrumPubController.cs
using System.Web.Mvc;
using Microsoft.AspNet.Identity;
using Valtech_Task3_Ankh_Morpork_MVC_.Services;

namespace Valtech_Task3_Ankh_Morpork_MVC_.Controllers
{
    public class TheMendedDrumPubController : Controller
    {
        // GET: TheMendedDrumPub
        public ActionResult Index()
        {
            return View();
        }
        [HttpPost]
        public ActionResult BuyBeer(int beer)
        {
            CurrentPlayerProcessor.CurrentPlayer =
                CurrentPlayerProcessor.PlayerManager.FindById(User.Identity.GetUserId());

            if (!CurrentPlayerProcessor.CurrentPlayer.IsBuyingBeer(beer)) return RedirectToAction("ToMuchBeerMan");

            CurrentPlayerProcessor.CurrentPlayer.LoseMoney(beer * 2);

            CurrentPlayerProcessor.PlayerManager.Update(CurrentPlayerProcessor.CurrentPlayer);

            return RedirectToAction("Ok");
        }

        public ActionResult Ok()
        {
            return View();
        }
        public ActionResult ToMuchBeerMan()
        {
            return View();
        }
    }
}

Valtech_Task3(Ankh-Morpork MVC)/Views/Shared/_GameProcessLayout.cshtml
@using Microsoft.AspNet.Identity
@using Valtech_Task3_Ankh_Morpork_MVC_.Services
<!DOCTYPE html>
<html>
<head>
    @Html.Partial("_ValidationMetaPartial")
    <title>@ViewBag.Title - My ASP.NET Application</title>
    @Html.Partial("_ValidationCssStylePartilal")
</head>
<body>
<div class="layout-header">
    <div class="image-position">
        <img src="~/img/ApplicationImages/logo.jpg" alt="logo image" width="60" height="60" />
    </div>
    <div class="logo-position">
        @Html.ActionLink("Ankh Morpork Game", "Index", "Home", null, new { @class = "link-style" })
    </div>
    @if (User.Identity.IsAuthenticated)
    {
        <div class="player-info">
            @using (Html.BeginForm("Logout", "Account", FormMethod.Post))
            {
                <input type="submit" value="Exit" class="button-exit">
            }
        </div>
        <div class="player-info">
            <p>Walker @CurrentPlayerProcessor.PlayerManager.FindById(User.Identity.GetUserId()).UserName</p>
        </div>
        <div class="player-info">
            <div>Step: @CurrentPlayerProcessor.CurrentPlayer.Step</div>
        </div>
        if (CurrentPlayerProcessor.CurrentPlayer.AmountOfBeer >= 0)
        {
            <div class="player-info">
                <div>Beer: @CurrentPlayerProcessor.CurrentPlayer.AmountOfBeer</div>
            </div>
        }
        <div class="player-info">
            <div>Balance: @CurrentPlayerProcessor.PlayerBalanceTextVariant(CurrentPlayerProcessor.GetCurrentPlayer(User.Identity.GetUserId()).Money)</div>
        </div>
    }
    else
    {
        <div class="player-info">
            @Html.ActionLink("Registration", "Register", "Account", null, new { @class = "link-style-enter" })
        </div>
        <div class="player-info">
            @Html.ActionLink("Login", "Login", "Account", null, new { @class = "link-style-enter" })
        </div>
    }
</div>
<div class="container">
    <div class="row">
        <div class="col-xs-12 col-sm-12 col-md-6 col-lg-10">
            <div class="gameplay_bord">
                @RenderBody()
            </div>
        </div>
        <div class="col-xs-12 col-sm-12 col-md-6 col-lg-2">
            <div class="pub-position">
                @if (CurrentPlayerProcessor.CurrentPlayer.Step % RandomGenerate.GetRandom(2, 9) == 0)
                {
                    <div class="pub-status">
                        Open
                    </div>
                    <a href="@Url.Action("Index", "TheMendedDrumPub")">
                        <img src="/img/ApplicationImages/beer.jpg" width="425" height="601" alt=""/>
                    </a>
                }
                else
                {
                    <div class="pub-status">
                        Close
                    </div>
                    <img src="/img/ApplicationImages/beerClose.jpg" width="425" height="601" alt=""/>
                }
            </div>
        </div>
    </div>
</div>
@Html.Partial("_ValidationScriptsPartial")
    @RenderSection("scripts", required: false)
</body>
</html>

Valtech_Task3(Ankh-Morpork MVC)/Views/Shared/_LayoutPage.cshtml
@using Microsoft.AspNet.Identity
@using Valtech_Task3_Ankh_Morpork_MVC_.Services
<!DOCTYPE html>
<html>
<head>
    @Html.Partial("_ValidationMetaPartial")
    <title>Ankh Morpork Game</title>
    @Html.Partial("_ValidationCssStylePartilal")
</head>
<body>
<div class="layout-header">
    <div class="image-position">
                <img src="~/img/ApplicationImages/logo.jpg" alt="logo image" width="60" height="60" />
            </div>
            <div class="logo-position">
                @Html.ActionLink("Ankh Morpork Game", "Index", "Home", null, new { @class = "link-style" })
            </div>
        @if (User.Identity.IsAuthenticated) 
            {
                <div class="player-info">
                    @using (Html.BeginForm("Logout", "Account", FormMethod.Post))
                        {
                            <input type="submit" value="Exit" class="button-exit">
                        }
                    </div>
                <div class="player-info" style="margin-top: -10px;">
                    @Html.ActionLink("Profile", "Index", "Player", null, new { @class = "link-style" })
                </div>
            }
            else
            {
                <div class="player-info">
                        @Html.ActionLink("Registration", "Register", "Account",null, new { @class = "link-style-enter" })
                    </div>
                <div class="player-info">
                        @Html.ActionLink("Login","Login","Account",null, new { @class = "link-style-enter" })
                </div>
            }
</div>
@RenderBody()
@Html.Partial("_ValidationScriptsPartial")
@RenderSection("scripts", required: false)
</body>
</html>

Valtech_Task3(Ankh-Morpork MVC)/Views/Shared/_ValidationCssStylePartilal.cshtml
@Styles.Render("~/Content/css")
@Styles.Render("~/Style/Style.css")
<link rel="preconnect" href="https://fonts.googleapis.com">
<link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
<link href="https://fonts.googleapis.com/css2?family=Gwendolyn&display=swap" rel="stylesheet">

Valtech_Task3(Ankh-Morpork MVC)/Views/Shared/_ValidationMetaPartial.cshtml
<meta charset="utf-8" />
<meta name="viewport" content="width=device-width, initial-scale=1.0">