Valtech_Task3(Ankh-Morpork MVC)/Controllers/GamePlayController.cs
using System.Web.Mvc;
using Microsoft.AspNet.Identity;
using Valtech_Task3_Ankh_Morpork_MVC_.Services;

namespace Valtech_Task3_Ankh_Morpork_MVC_.Controllers
{
    public class GamePlayController : Controller
    {
        private GameEngine _gameEngine => new GameEngine(User.Identity.GetUserId());
        // GET: GamePlay
        public ActionResult Index()
        {
            _gameEngine.Step();
            return RedirectToAction("Index", GuildProcessor.GetRandomGuild());
        }
        public ActionResult GameOver()
        {
            GameEngine.MoneyChecker = CurrentPlayerProcessor.CurrentPlayer.Money;
            return View();
        }
        public ActionResult Play()
        {
            _gameEngine.StartInitialization();
            return RedirectToAction("Index");
        }
    }
}

Valtech_Task3(Ankh-Morpork MVC)/Controllers/TheMendedDrumPubController.cs
using System.Web.Mvc;
using Microsoft.AspNet.Identity;
using Valtech_Task3_Ankh_Morpork_MVC_.Services;

namespace Valtech_Task3_Ankh_Morpork_MVC_.Controllers
{
    public class TheMendedDrumPubController : Controller
    {
        // GET: TheMendedDrumPub
        public ActionResult Index()
        {
            return View();
        }
        [HttpPost]
        public ActionResult BuyBeer(int beer)
        {
            CurrentPlayerProcessor.CurrentPlayer =
                CurrentPlayerProcessor.PlayerManager.FindById(User.Identity.GetUserId());

            if (!CurrentPlayerProcessor.CurrentPlayer.IsBuyingBeer(beer)) return RedirectToAction("ToMuchBeerMan");

            CurrentPlayerProcessor.CurrentPlayer.LoseMoney(beer * 2);

            CurrentPlayerProcessor.PlayerManager.Update(CurrentPlayerProcessor.CurrentPlayer);

            return RedirectToAction("Ok");
        }

        public ActionResult Ok()
        {
            return View();
        }
        public ActionResult ToMuchBeerMan()
        {
            return View();
        }
    }
}

Valtech_Task3(Ankh-Morpork MVC)/Views/TheMendedDrumPub/Index.cshtml
@{
    Layout = "~/Views/Shared/_GameProcessLayout.cshtml";
}
<div class="gameplay-info-position">
    <div style="height: 80%;">
        <h2>You in the Mended Drum Pub how much beer do you want to buy?</h2>
        @using (Html.BeginForm("BuyBeer", "TheMendedDrumPub", FormMethod.Post))
        {
            <input type="number" name="beer" required="required" class="authorization-login"/>
            <br/>
            <input type="submit" name="Send" class="button-for-assassin"/>
        }
    </div>
    <div style="height: 20%;">
        <a href='javascript:history.go(-1)' class="link-style">Previous Page</a>
    </div>
</div>

Valtech_Task3(Ankh-Morpork MVC)/Views/TheMendedDrumPub/Ok.cshtml
@{
    Layout = "~/Views/Shared/_GameProcessLayout.cshtml";
}
<div class="gameplay-info-position">
    <div style="height: 80%">
        <h2>Congratulations on your successful purchase. Come back soon my friend!</h2>
    </div>
    <div style="height: 20%">
        <div class="authorization-variants">
            @Html.ActionLink("Next step", "Index", "GamePlay", null, new { @class = "link-style" })
        </div>
    </div>
</div>

Valtech_Task3(Ankh-Morpork MVC)/Views/TheMendedDrumPub/ToMuchBeerMan.cshtml
@using Valtech_Task3_Ankh_Morpork_MVC_.Services

@{
    Layout = "~/Views/Shared/_GameProcessLayout.cshtml";
}
<div class="gameplay-info-position">
    <div style="height: 80%;">
        <h2>You have too much beer and should not exceed 2 pints of beer!</h2>
    </div>
    <div style="height: 20%;">
        @if (CurrentPlayerProcessor.CurrentPlayer.AmountOfBeer <= 1)
        {
            <h2>You can have only 2 pints of beer! Now you have @CurrentPlayerProcessor.CurrentPlayer.AmountOfBeer pints of beer</h2>
            <a href='javascript:history.go(-1)' class="link-style">Go to previous stage and choose another amount of beer!</a>
        }
        else
        {
            <a href='javascript:history.go(-2)' class="link-style">Go Back to the game coz you have max value of beer!</a>
        }
    </div>
</div>