Valtech_Task3(Ankh-Morpork MVC)/Controllers/GuildsController/AssassinsGuildController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web.Mvc;
using Microsoft.AspNet.Identity;
using Valtech_Task3_Ankh_Morpork_MVC_.DataManager.Context;
using Valtech_Task3_Ankh_Morpork_MVC_.DataManager.Repository;
using Valtech_Task3_Ankh_Morpork_MVC_.Guilds;
using Valtech_Task3_Ankh_Morpork_MVC_.Models;
using Valtech_Task3_Ankh_Morpork_MVC_.Services;

namespace Valtech_Task3_Ankh_Morpork_MVC_.Controllers.GuildsController
{
    [Authorize]
    public class AssassinsGuildController : Controller
    {
        private CurrentPlayerProcessor _playerProcessor = new CurrentPlayerProcessor();

        private readonly AssassinsRepository _assassinsRepository =
            new AssassinsRepository(AssassinsDbContext.Create());

        // GET: AssassinsGuild
        public ActionResult Index()
        {
            return View();
        }
        public ActionResult Action()
        {
            return View();
        }

        [HttpPost]
        public ActionResult Action(decimal money)
        {
            var listOfAvailableAssassins = _assassinsRepository.GetGuildMembersEnumerable.Where(assassin =>
                assassin.IsOccupied == false && (assassin.MinRange <= money && money <= assassin.MaxRange)).ToList();

            if (listOfAvailableAssassins.Any())
            {
                CurrentPlayerProcessor.CurrentPlayer = CurrentPlayerProcessor.PlayerManager.FindById(User.Identity.GetUserId());

                CurrentPlayerProcessor.CurrentPlayer.LoseMoney(money);

                CurrentPlayerProcessor.PlayerManager.Update(CurrentPlayerProcessor.CurrentPlayer);

               AssassinsGuild.ChangeOccupiedAssassins(_assassinsRepository,listOfAvailableAssassins);
            }

            if (CurrentPlayerProcessor.CurrentPlayer.Money <= 0)
                return RedirectToAction("OutOfMoney", "Player");

            TempData["availableAssassins"] = listOfAvailableAssassins;

            return RedirectToAction("AvailableAssassins");
        }

        public ActionResult AvailableAssassins()
        {
            var listAssassinsEnumerable = TempData["availableAssassins"] as IEnumerable<Assassins>;

            return View(listAssassinsEnumerable);
        }
        public ActionResult AnswerYes()
        {
            return RedirectToAction("Action");
        }

        public ActionResult AnswerNo()
        {
            return RedirectToAction("GameOver", "GamePlay");
        }
    }
}

Valtech_Task3(Ankh-Morpork MVC)/Views/AssassinsGuild/Action.cshtml
@{
    Layout = "~/Views/Shared/_GameProcessLayout.cshtml";
}
<div class="gameplay-info-position">
    <div style="height: 80%;">
        <h2>Enter the desired amount of money in range 4-45 AM$</h2>
    </div>
    <div style="height: 20%; margin-left: 300px; margin-top: -40px;">
        @using (Html.BeginForm("Action", "AssassinsGuild", FormMethod.Post))
        {
            <input type="number" name="money" required="required" class="authorization-login"/>
            <br/>
            <input type="submit" name="Send" class="button-for-assassin"/>
        }
    </div>
</div>

Valtech_Task3(Ankh-Morpork MVC)/Views/AssassinsGuild/AvailableAssassins.cshtml
@model IEnumerable<Valtech_Task3_Ankh_Morpork_MVC_.Models.Assassins>
@{
    Layout = "~/Views/Shared/_GameProcessLayout.cshtml";
}
<div class="gameplay-info-position">
    @if (!Model.Any())
    {
        <div style="height: 80%">
            <h2>All assassins are occupied or amount of money to low or to much! Enter the amount in the range 4-45 dollars!</h2>
        </div>
        <div style="height: 20%">
            <div class="authorization-variants">
                @Html.ActionLink("Make another answer", "Action", null, new { @class = "link-style" })
            </div>
        </div>
    }
    else
    {
        <div style="height: 80%;">
            @if (Model.Count() == 1)
            {
            <h2>The entered amount is suitable for one assassin. You pay exactly to him!</h2>
            }
            else
            {
            <h2>The entered amount is suitable for @Model.Count() assassins! You pay to first of them! Money goes to @Model.ElementAtOrDefault(0) !</h2>
            }
            @foreach (var assassin in Model)
            {
            <div class="assassins-list">
                <h2 style="text-align: center; font-weight: bold;">@assassin.Name</h2>
                <img src="~/img/AssassinsImages/@(assassin.ImageName)" height="250" alt="" />
            </div>
            }
        </div>
        <div style="height: 20%;">
            <div class="authorization-variants anothestyle">
                @Html.ActionLink("Next step", "Index", "GamePlay", null, new { @class = "link-style" })
            </div>
        </div>
    }
</div>

Valtech_Task3(Ankh-Morpork MVC)/Views/AssassinsGuild/Index.cshtml
@{
    Layout = "~/Views/Shared/_GameProcessLayout.cshtml";
}
<div class="gameplay-info-position">
    <div style="height: 80%">
        <h2>Someone wishes you death. In order to protect yourself, you need to take a contract from the assassin, but it will cost a certain amount of money. </h2>
        <h2>Do you agree to take on the contract? </h2>
    </div>
    <div style="height: 20%">
        <div class="authorization-variants">
            @Html.ActionLink("Yes", "AnswerYes", null, new { @class = "link-style" })
        </div>
        <div class="authorization-variants">
            @Html.ActionLink("No", "AnswerNo", null, new { @class = "link-style" })
        </div>
    </div>
</div>